name: Clean up untagged GHCR images

on:
  schedule:
    # Run every Sunday at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch: # Allow manual trigger

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Debug package information
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Repository name: ${{ github.event.repository.name }}"
          echo "Repository owner: ${{ github.repository_owner }}"
          echo "Expected package name: ${{ github.event.repository.name }}"

      - name: Check if packages exist
        run: |
          # Try to list packages to see what's available
          curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/user/packages?package_type=container" || true

      - name: Delete untagged images only
        uses: snok/container-retention-policy@v3.0.0
        with:
          account: user
          token: ${{ secrets.GITHUB_TOKEN }}
          image-names: ${{ github.repository }}
          tag-selection: untagged
          cut-off: 1d
          dry-run: true # Enable dry-run first to debug
          rust-log: container_retention_policy=debug # More detailed logging

      - name: Log cleanup completion
        run: |
          echo "GHCR cleanup completed at $(date)"
          echo "Deleted untagged images for repository: ${{ github.repository }}"